_format_version: "2.1"
_transform: true

services:
  - name: appone
    url: http://host.docker.internal:8081
    routes:
      - name: appone-route
        paths:
          - /appone
  - name: apptwo
    url: http://host.docker.internal:8082
    routes:
      - name: apptwo-route
        paths:
          - /apptwo
  - name: appthree
    url: http://host.docker.internal:8083
    routes:
      - name: appthree-route
        paths:
          - /appthree
  # - name: admin-api
  #   url: http://localhost:8001
  #   routes:
  #     - paths:
  #         - /admin-api

consumers:
  - username: my-user

jwt_secrets:
  - algorithm: HS256
    consumer: my-user
    key: kungfupandais110%fit
    secret: yoursecretissafe100%

plugins:
  - name: kong-jwt2header
    enabled: true
    config:
      strip_claims: "true"
      token_required: "false"

  - name: jwt
    config:
      key_claim_name: kid

  - name: rate-limiting
    config:
      second: 5
      minute: 10
      hour: 1000
      policy: local




  
 